# Generated by Django 3.1.7 on 2021-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('publisher', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('is_checked_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comicuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='ComicBaseApp.ComicBook'),
        ),
    ]
