# Generated by Django 3.1.7 on 2021-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0002_auto_20210412_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
