# Generated by Django 3.1.7 on 2021-04-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0003_auto_20210412_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='comicuser',
            name='favorites',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ComicBaseApp.comicbook'),
        ),
    ]
