# Generated by Django 3.1.7 on 2021-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0005_auto_20210412_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='comicuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='ComicBaseApp.ComicBook'),
        ),
    ]
