# Generated by Django 3.1.7 on 2021-04-13 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0006_auto_20210412_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicuser',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
