# Generated by Django 3.1.7 on 2021-04-13 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0007_comicuser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicuser',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
