# Generated by Django 3.1.7 on 2021-04-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0008_auto_20210413_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comicbook',
            name='lg_image',
            field=models.URLField(default=''),
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comicbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comicbook', to='ComicBaseApp.comicbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comicuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comicuser',
            name='holds',
            field=models.ManyToManyField(blank=True, related_name='holds', to='ComicBaseApp.Hold'),
        ),
    ]
