# Generated by Django 3.1.7 on 2021-04-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBaseApp', '0009_auto_20210415_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicuser',
            name='checkedout_comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkedout_comic', to='ComicBaseApp.comicbook'),
        ),
        migrations.AlterField(
            model_name='comicuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
